CREATE TABLE `fiveware`.`pessoa` (
  `PESSOA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PESSOA_NOME` varchar(45) NOT NULL,
  `PESSOA_STATUS_CIVIL` varchar(45) DEFAULT NULL,
  `PESSOA_DEFICIENTE` bit(1) DEFAULT NULL,
  `PESSOA_SEXO` varchar(9) DEFAULT NULL,
  PRIMARY KEY (`PESSOA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#PODERIA SER MELHOR ESPECIFICADO COM RESTRAINTS QUANTO AOS TIPOS
#DE DADOS QUE PODEM SER INSERIDOS

/* Populate USER_PROFILE Table */
INSERT INTO `fiveware`.`pessoa` (`PESSOA_NOME`,`PESSOA_STATUS_CIVIL`, `PESSOA_DEFICIENTE`,`PESSOA_SEXO`)
VALUES ('Stephen Hawkins','CASADO',1,'MASCULINO');
  
INSERT INTO `fiveware`.`pessoa` (`PESSOA_NOME`,`PESSOA_STATUS_CIVIL`, `PESSOA_DEFICIENTE`,`PESSOA_SEXO`)
VALUES ('Natasha Romanoff','SOLTEIRO',0,'FEMININO');
  
INSERT INTO `fiveware`.`pessoa`  (`PESSOA_NOME`,`PESSOA_STATUS_CIVIL`, `PESSOA_DEFICIENTE`,`PESSOA_SEXO`)
VALUES ('Bruce Banner','SOLTEIRO',0,'MASCULINO');

commit;